// src/export/zip.ts
//
// Pure ZIP packager. Takes a `quiz.md`, `quiz.json`, `manifest.json`, and a
// map of asset localPaths → bytes, and returns a `Uint8Array` containing
// the final ZIP archive (built with `fflate.zipSync`).
//
// The packager is deliberately pure: no `browser.*`, no DOM, no fetch.
// That makes it trivial to unit-test with golden bytes and lets the
// orchestrator feed in stub bytes from the AssetFetchClient.

import { zipSync, strToU8 } from 'fflate';
import { redactString } from '~/diagnostics/redactor';

export interface ZipInput {
  /** Markdown body. Goes to `quiz.md` at the archive root. */
  readonly markdown: string;
  /** Canonical JSON serialization. Goes to `quiz.json`. */
  readonly json: string;
  /** Manifest JSON. Goes to `manifest.json`. */
  readonly manifest: string;
  /** Asset bytes keyed by their local path inside the ZIP (e.g. "quiz/q1-…png"). */
  readonly assets: ReadonlyMap<string, Uint8Array>;
  /** Filename of the ZIP inside the archive (used for README only). */
  readonly archiveLabel?: string;
}

/** Build a ZIP from the inputs. Every string is run through the redactor
 *  before serialization so any leak throws synchronously instead of
 *  shipping in the final file. The manifest JSON and the canonical
 *  QuizDocument JSON, however, may contain computed SHA-256 fingerprints
 *  (originHash, asset sha256, generatorVersion) — these are bypassed
 *  because they are public by design.
 *
 *  In practice the orchestrator passes a manifest that has already been
 *  through `buildManifest()`, which only redacts user-derived fields, and
 *  a `quiz.json` whose `source.originHash` is the public SHA-256 of the
 *  origin (NOT a leaked session id). */
export function buildZip(input: ZipInput): Uint8Array {
  // Markdown has no computed fingerprints; it is fully redacted.
  const markdown = redactString(input.markdown);
  // quiz.json and manifest.json both contain computed hex fingerprints —
  // exempt those fields from the canary scan.
  const json = redactJsonAllowingFingerprints(input.json);
  const manifest = redactJsonAllowingFingerprints(input.manifest);
  const archiveLabel = input.archiveLabel
    ? redactString(input.archiveLabel)
    : 'moodle-quiz-extractor export';

  const entries: Record<string, Uint8Array> = {};
  entries['README.txt'] = strToU8(
    [
      'moodle-quiz-extractor export',
      '',
      `Generated by: ${archiveLabel}`,
      '',
      'Contents:',
      '  - quiz.md         human-readable export (Markdown)',
      '  - quiz.json       canonical QuizDocument (Zod schema "1.0")',
      '  - manifest.json   sidecar manifest with provenance and asset list',
      '  - quiz/*          downloaded asset files',
      '',
      'Privacy: this archive was double-redacted. If you see a session token,',
      '          sesskey, attempt id, cmid, or input name, please file a bug.',
    ].join('\n'),
  );
  entries['quiz.md'] = strToU8(markdown);
  entries['quiz.json'] = strToU8(json);
  entries['manifest.json'] = strToU8(manifest);

  for (const [localPath, bytes] of input.assets) {
    const path = redactString(localPath);
    if (path.includes('..') || path.startsWith('/')) {
      throw new Error(`asset path escapes archive root: ${path}`);
    }
    entries[path] = bytes;
  }

  // fflate's level 6 is a good speed/ratio tradeoff for ~hundreds of KB.
  return zipSync(entries, { level: 6 });
}

/** Redact a JSON string while leaving the public fingerprint fields alone
 *  (`originHash`, `sha256`, `stableFingerprint`, `generatorVersion`).
 *  Non-JSON input is fully redacted (treats it as opaque text). */
function redactJsonAllowingFingerprints(input: string): string {
  let parsed: unknown;
  try {
    parsed = JSON.parse(input);
  } catch {
    return redactString(input);
  }
  walk(parsed);
  return JSON.stringify(parsed, null, 2);

  function walk(node: unknown, path = '$'): void {
    if (!node || typeof node !== 'object') return;
    if (Array.isArray(node)) {
      for (let i = 0; i < node.length; i += 1) walk(node[i], `${path}[${i}]`);
      return;
    }
    const obj = node as Record<string, unknown>;
    for (const key of Object.keys(obj)) {
      const value = obj[key];
      if (FINGERPRINT_KEYS.has(key) && typeof value === 'string') {
        continue;
      }
      if (typeof value === 'string') {
        obj[key] = redactString(value);
      } else if (value && typeof value === 'object') {
        walk(value, `${path}.${key}`);
      }
    }
  }
}

/** Computed SHA-256 fields that are public by design. Anything in this
 *  set is exempt from the canary scan because its hex shape would
 *  otherwise match the `long-hex-blob` canary. */
const FINGERPRINT_KEYS: ReadonlySet<string> = new Set([
  'originHash',
  'sha256',
  'stableFingerprint',
  'generatorVersion',
]);