// tests/unit/exclude-sources.spec.ts
//
// Verifies that the source zip generated by `pnpm zip:firefox`
// excludes the developer's raw HTML fixtures (resources/) which carry
// real sesskey / MoodleSession values.

import { describe, it, expect } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const sourcesZip = join(
  ROOT,
  '.output',
  'moodle-quiz-extractor-0.4.0-sources.zip',
);
const skip = !existsSync(sourcesZip);

const runIfBuilt = skip ? describe.skip : describe;

runIfBuilt('excludeSources: resources/ excluded from source zip', () => {
  it('source zip does NOT list resources/*.html', () => {
    const out = execFileSync('unzip', ['-l', sourcesZip], { encoding: 'utf8' });
    expect(out).not.toMatch(/resources\/.*\.html/);
  });

  it('source zip DOES list tests/fixtures/redacted/ fixtures', () => {
    const out = execFileSync('unzip', ['-l', sourcesZip], { encoding: 'utf8' });
    expect(out).toMatch(/tests\/fixtures\/redacted\/dsop-01-page-01\.html/);
  });

  it('source zip includes tools/redact-fixture.mjs', () => {
    const out = execFileSync('unzip', ['-l', sourcesZip], { encoding: 'utf8' });
    expect(out).toMatch(/tools\/redact-fixture\.mjs/);
  });
});
